### PR TITLE
DocStrings

### PR DESCRIPTION
**Pull request by mattwynne**

### CODE REVIEW

**Comment by jowers** [comment]
Finally got around to having a go at this.

I've got it passing, although came across a couple of things that may need adjusting:

In step_definitions.rb, as I was struggling trying to find out the name of the object for multiline_args, I've used `if multiline_arg.respond_to?('content')`

I've assumed that in the case there are both regexp captures and a doc_string, the last parameter to a step definition is the doc_string.

The step_name for a doc string came through with a colon on the end - I'm not sure about correct gherkin syntax for this, but to get this passing, I've added a line to strip off any trailing colons from the step_name. How is that handled in ruby cucumber?

**Comment by mattwynne** [comment]
The colon is incidental detail - I just have a habit of using them when I write a step before a multiline arg in Gherkin, but there's nothing special about it.

**Comment by jowers** [comment]
I've removed the stuff about the colon and modified the feature file so that the regexp match includes a colon.

There is also a bonus check-in because I forgot to pull in the changes you'd made first

**Comment by mattwynne** [comment]
Nice work @jowers!

**Pull request closed without merging**
