### PR TITLE
Add namespaces

### PR DESCRIPTION
**Pull request by jowers**
I've modified framework.tcl to use namespaces instead of living in the global scope. All the tests passes, but I'll try to get someone else to have a look over it in case I've done something stupid.

Once this is done, we should be able to look at a more complete set of table functions.

### CODE REVIEW

**Comment by jimmydavies** [comment]
Not sure if this is the best place for these comments but I'm on my phone and can't see a better place (bit new to git hub)

* would it not make sense to also export the procs Given, When, Then, And. Otherwise would the steps in the feature file end up needing to use the fully qualified proc names. My guess is that all the procs you want in natural language should be exported and anything else shouldn't

Other than that it looks fine from a tcl point of view, there's a couple of things that could be changed for neatness sake but they don't really add anything to this feature so I don't think they are relevant. Specifically packaging over sourcing, avoid init on source and simplify the source_steps proc

**Comment by jowers** [comment]
Welcome to the project Jimmy!

Perfect place for the comments.

I think it makes sense for the Given/When/Then to be exported, so I'll do that now (I had to export the other 2 procs so that the call from ruby worked)

I'd be interested in seeing what it would look like with your other changes (i.e. packages, etc) - maybe we can get this change merged back and then you can create a branch with those modifications on?

**Comment by jowers** [comment]
Ok, I've made those changes (also removed the And proc which shouldn't be there, as in core cucumber, only Given, When and Then are valid step proc names). 

@jimmydavies, @mattwynne  are you ok for me to merge this one back?

**Comment by mattwynne** [comment]
OK with me.

**Comment by jimmydavies** [comment]
Yeah, looks good to me

**Pull request closed without merging**
