### PR TITLE
Reset state between scenarios

### PR DESCRIPTION
**Pull request by mattwynne**
@jowers what do you think? Will this do for now?

### CODE REVIEW

**Comment by jowers** [comment]
My head has seen too much code today! I'll take a look through this one tomorrow

**Comment by jowers** [comment]
I don't think the feature is quite right. Either we should make the variable being defined in the namespace into a namespace variable (e.g. `variable g` rather than `global g`) or we should do away with the namespace altogether and just use a global. When I ran a similar scenario as above against the master version, it was also unable to access them.

I'll check in the version with globals as that is closer to the decscription of the feature, and having the namespace doesn't really add anything to the behaviour.

**Comment by mattwynne** [comment]
Ok great. I tried using global initially but my tcl-fu was too weak.

Typed with my Thumbs.

**Comment by jowers** [comment]
Cool. Are you happy for us to merge this one back to main?

**Comment by mattwynne** [comment]
Yes. Can you do it with a `--squash`?

**Comment by jowers** [comment]
Merged to master

**Pull request closed without merging**
