### PR TITLE
Add licence

### PR DESCRIPTION
**Pull request by mlvandijk**
Based on cucumber/docs.cucumber.io#304

### CODE REVIEW

**Comment by mlvandijk** [comment]
Not sure how to fix the CI failure...

**Comment by jowers** [comment]
Hmmm, looks like circleci is not able to checkout the code. It's not had a new build for a while, so possibly something changed when 2FA was required? @mattwynne you set this up originally, are there any pointers you could give to me or @ahhbristow about getting this running again?

**Comment by mattwynne** [comment]
I think the problem is that the project is using Circle 1.0 config format which is now turned off.

**Comment by mattwynne** [comment]
I've had a crack at setting up a Circle 2.0 build in #42. If that works we can rebase this on top and it should pass fine.

**Pull request merged**
