### PR TITLE
Travis build

### PR DESCRIPTION
**Pull request by mattwynne**
Ref #2

### CODE REVIEW

**Comment by mattwynne** [comment]
@cucumber/cucumber-tcl any ideas why this won't build? See https://travis-ci.org/cucumber/cucumber-ruby-tcl/builds/49820413 for example. I'm using tcl 8.6 from source.

**Comment by jowers** [comment]
Yep - the code in the ruby-tcl package does a few things which were deprecated in tcl8.5 and removed in tcl 8.6 by the looks of things. I hit a similar problem late last night. When I used tcl8.5, I still got the warnings, but no errors.

I suspect we'll want to suggest a few pull requests to the ruby-tcl package in future, but for our purposes, we haven't yet moved to tcl8.6, so 8.5 will be ok for our immediate requirements.

**Comment by mattwynne** [comment]
OK with TCL 8.5 this is now looking good. I just need to fix some problems with Cucumber versions - using the master branch like this is too much of a hack.

**Comment by mattwynne** [comment]
@jowers any ideas why that `so` file can't be found now?

**Pull request closed without merging**
